name: Release

on:
  push:
    tags:
      - "**"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${github.ref_name}
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'polka-v')
      - run: echo "some other thing"
        if: github.ref_type == 'tag' && !startsWith(github.ref_name, 'polka-v')
