name: Release

on:
  push:
    tags:
      - "**-v*.*.*"

jobs:
  echo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag_name:
          - a
          - b

    steps:
      - run: echo ${github.ref_name}
